@client.command(pass_context = True)
@commands.has_permissions(ban_members=True)
async def ban(ctx, member : discord.Member, *, reason=None):
    embed = discord.Embed(colour = (clienthex),title = ('Banned'),description = (f'Banned {member}'), timestamp = (ctx.message.created_at))
    embed.set_author(name=f"{member}", icon_url=member.avatar.url)
    embed.set_thumbnail(url=member.avatar.url)
    embed.add_field(name='Reason', value=(f"""{reason}"""), inline=False)
    await member.ban(reason=reason)
    await ctx.send(embed=embed)
    await ctx.message.delete()
