@client.command(aliases=['emojifo'])
@commands.has_permissions(manage_emojis=True)
async def emojiinfo(ctx, emoji : discord.PartialEmoji):
    name = (emoji.name)
    id = (emoji.id)
    animated = (emoji.animated)
    time = (emoji.created_at)
    url = (emoji.url)
    embed = discord.Embed(colour=clienthex, timestamp=ctx.message.created_at)
    embed.set_author(name=name, icon_url=url)
    embed.set_thumbnail(url=url)
    embed.set_footer(text=f"Requested by {ctx.message.author}", icon_url=url)
    embed.add_field(name="Name:", value=name)
    embed.add_field(name="ID:", value=id)
    embed.add_field(name="Animated", value=animated)
    embed.add_field(name="Created at:", value=time)
    embed.add_field(name="Url:", value=url)
    await ctx.send(embed=embed)
    await ctx.message.delete()
