@client.command(pass_context = True)
async def tod(ctx):
    possible_responses = [
        """Try eating something while wearing a blindfold.""",
        """Dance with no music.""",
        """Do the Macarena.""",
        """Act out a funny story.""",
        """Tell jokes until another player laughs.""",
        """Talk with a different accent every time you say something until the end of the game.""",
        """Sing a song without opening your mouth and let the other players guess the song.""",
        """Dance like a ballet dancer.""",
        """Stack some items to build the tallest tower possible.""",
        """Give a piggyback to another player.""",
        """Choose a random item in the room and make up a story about it.""",
        """What is your deepest secret?""",
        """Do you have any phobias?""",
        """What makes you feel ashamed?""",
        """What is the most embarrassing thing that has ever happened to you?""",
        """What is the biggest mistake you have ever made?""",
        """What is something you are not good at?""",
        """What is the biggest lie you have ever told?""",
        """Have you ever been caught picking your nose?""",
        """Have you ever skipped a shower?""",
        """Do you sing in the shower?""",
        """Have you ever cheated when playing a game?""",
        """What is a weird habit that you have?""",
        """What is the most childish thing that you still do?""",
        """Call a friend and explain the rules of your favorite board game without giving them an explanation.""",
        """Everything you say has to rhyme until the next turn.""",
        """Take a silly picture.""",
        """Talk with a silly voice until the end of the game.""",
        """Let another player put lipstick on you.""",
        """Keep water in your mouth while other players try to make you laugh.""",
        """Talk for five minutes without stopping.""",
        """Hop around the other players.""",
        """Draw something on your arm with a marker.""",
        """Go outside and hug all the trees in the backyard.""",
        """Peel a banana with your teeth.""",
        """Go outside and do a rain dance.""",
        """Yell some random exclamations during the entire game.""",
        """Stand on your head.""",
        """Go outside in your pajamas.""",
        """Let other players paint your nails.""",
        """Drink an entire can of soda in ten seconds or less.""",
        """When was the last time you forgot something?""",
        """What is your least favorite thing to do?""",
        """Who is your silliest friend?""",
        """What is the silliest thing you have ever done?""",
        """What is the silliest rule we have at home?""",
        """If you could misbehave without consequences, what would you do?""",
        """What is the most useless thing you know?""",
        """What is the ugliest item of clothing you own?""",
        """What is the strangest dream you’ve ever had?""",
        """Have you ever worn clothes that didn’t match?""",
        """What is the worst haircut you ever got?""",
        """What is the silliest thing that you regret?""",
        """What is the worst thing that you’ve ever done?""",
        """What is your least favorite food?""",
        """What is the worst joke you have ever heard?""",
        """What is your signature dance move?""",
        """What is a question that you refuse to answer?""",
        """Would you rather be late or early?""",
        """What is a movie title that describes your life?""",
        """Do you think ghosts are real?""",
        """Run around the house three times.""",
        """Do jumping jacks until the next turn.""",
        """Let another player style your hair.""",
        """Crawl like a worm.""",
        """Dance to a song chosen by another player.""",
        """Make animal noises.""",
        """Don’t speak until the next turn.""",
        """Say the alphabet backward.""",
        """Sing a nursery rhyme.""",
        """Make up a song.""",
        """Stand up until the next turn.""",
        """Don’t move for an entire minute.""",
        """Tell a joke.""",
        """Go steal a snack from the fridge.""",
        """Recite a poem.""",
        """Wear a towel as a cape for the entire duration of the game.""",
        """Try singing with marshmallows in your mouth.""",
        """Balance a spoon on your nose.""",
        """Go outside and act like a chicken for ten minutes.""",
        """What is your favorite color?""",
        """Do you have a favorite animal?""",
        """What makes you happy?""",
        """What is your favorite day of the week?""",
        """What is your dream job?""",
        """What would you say to your stuffed animals if they could understand you?""",
        """If you opened a restaurant, what kind of food would you serve?""",
        """What is your favorite memory?""",
        """Who is your favorite teacher?""",
        """What is your favorite storybook?""",
        """If you could become a cartoon character, who would it be?""",
        """Which rule would you change if you were in charge at home?""",
        """What is a skill that you would like to learn?""",
        """What does your dream home look like?""",
        """If you started a band, what would you name it?""",
        """What is your favorite video game?""",
        """What is the one thing you couldn’t live without?""",
        """What is your favorite vacation spot?""",
        """Go outside and wave at the people you see.""",
        """Try to moonwalk.""",
        """Borrow an item of clothing from another player and wear it until the next turn.""",
        """Pour some cold water on your head.""",
        """Eat some crackers and try to whistle.""",
        """Wear socks on your hands until the next turn.""",
        """Hold your breath for ten seconds.""",
        """Try jumping on one foot.""",
        """Wear a silly hat until the next turn.""",
        """Talk with a foreign accent until the next turn.""",
        """Do ten pushups.""",
        """Go get an item from another room while wearing a blindfold.""",
        """Try juggling with some eggs.""",
        """Wear your socks on your hands until the next turn.""",
        """Mix different soft drinks and drink the mixture.""",
        """Speak in a made-up language until the next turn.""",
        """What is your biggest pet peeve?""",
        """If you could change one thing about yourself, what would it be?""",
        """What is the one food you couldn’t live without?""",
        """What is the scariest movie you have ever seen?""",
        """Which book would you take on a deserted island?""",
        """If you could travel in time, which decade would you want to visit?""",
        """What is the strangest dream you’ve ever had?""",
        """What are you most afraid of?""",
        """Do you have a nickname?""",
        """What is your favorite song to sing along to?""",
        """What is the one food you couldn’t live without?""",
        """Which country would you like to visit?""",
        """What is the best surprise you ever got?""",
        """If you were a superhero, which powers would you want to have?""",
        """Which animal is most like you?""",
        """What is your favorite outfit to wear?""",
        """What is the subject you like the most at school?""",
        """What is your favorite TV show?""",
        """What is your favorite holiday tradition?""",
        """What annoys you the most?""",
        """If you won a million dollars, what is the first thing you would buy?""",
        """What is your favorite store to shop at?""",
        """If you could change one thing about your past, what would it be?""",
        """If you had three wishes, what would they be?""",
        """Go outside and yell “Merry Christmas!”""",
        """Go next door and ask the neighbors to borrow a random item.""",
        """Lick your elbow.""",
        """Sing a song with a silly voice.""",
        """Don’t laugh while the other players try to make you laugh.""",
        """Imitate another player.""",
        """Do a silly dance.""",
        """Eat a spoonful of sugar.""",
        """Drink a glass of water with salt in it.""",
        """Prank call a friend.""",
        """Try to do a cartwheel.""",
        """Eat something without using your hands.""",
        """Try not to blink for 30 seconds.""",
        """Imitate a cartoon character.""",
        """Hold an ice cube in your hand until it melts.""",
        """Talk with your tongue sticking out.""",
        """Draw or write something while holding the pen in your mouth.""",
        """Eat a spoonful of peanut butter and try singing.""",
        """Try saying something with your mouth closed.""",
        """Talk using the third person until the next turn.""",
        """Sing every time you want to say something until the next turn.""",
        """Spin ten times and try performing a simple task.""",
        """Talk and act like a cowboy.""",
        """Stand on your hands.""",
        """Draw something blindfolded.""",
        """What is the last lie you told?""",
        """When was the last time you cleaned up your room?""",
        """Have you ever broken something in the house and blamed a sibling?""",
        """What was your most embarrassing moment?""",
        """What is the funniest thing you have ever seen?""",
        """When was the last time you laughed?""",
        """Who is your funniest friend, and why?""",
        """Which cartoon characters does the player to your right look like?""",
        """Have you ever snooped to find what you were getting for Christmas?""",
        """What is your weirdest talent?""",
        """What is the funniest thing that ever happened at school?""",
        """What is your favorite joke?""",
        """What is the funniest thing the family pet has ever done?""",
        """Have you ever played a prank on someone?""",
        """What is the clumsiest thing you have ever done?""",
        """What is something you would never admit to anyone?""",
        """What is the weirdest thing about your family?""",
    ]
    await ctx.send(random.choice(possible_responses)+ctx.message.author.mention)
